apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-nodejs-wlkhhscy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-nodejs-wlkhhscy 
  name: github-tests-nodejs-wlkhhscy
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: github-tests-nodejs-wlkhhscy
    weight: 100 
